import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

const venues = [
  // MUMBAI (8)
  {
    name: 'Taj Mahal Palace',
    description: 'Iconic heritage hotel on the Apollo Bunder waterfront. Grand ballrooms, stunning sea views, and impeccable Taj service. Perfect for royal weddings and luxury corporate galas.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 285,
    pricePerDay: 1500000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Taj+Mahal+Palace/@18.9218,-72.8332,17z',
    capacity: 1500,
  },
  {
    name: 'The Oberoi Mumbai',
    description: 'Sleek luxury tower overlooking the Arabian Sea. Contemporary interiors with world-class F&B. Ideal for high-profile corporate events and intimate luxury weddings.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 287,
    pricePerDay: 1200000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+Mumbai/@18.9649,-72.8103,17z',
    capacity: 800,
  },
  {
    name: 'Four Seasons Hotel Mumbai',
    description: 'Soaring glass tower in Worli with panoramic city and sea views. Stylish event spaces with cutting-edge AV infrastructure. The go-to for fashion shows and premieres.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 202,
    pricePerDay: 1100000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/Four+Seasons+Hotel+Mumbai/@19.0037,-72.8189,17z',
    capacity: 600,
  },
  {
    name: 'The St. Regis Mumbai',
    description: 'Mumbai\'s tallest hotel offering unmatched skyline views. Exquisite banquet halls with butler service and curated menus. Perfect for grand weddings and luxury conferences.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 395,
    pricePerDay: 1300000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+St.+Regis+Mumbai/@19.0768,-72.8777,17z',
    capacity: 1000,
  },
  {
    name: 'JW Marriott Mumbai Juhu',
    description: 'Beachfront luxury hotel at Juhu with golden sand views. Spacious pillar-less ballrooms and lush outdoor lawns. Excellent choice for Bollywood-style celebrations.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 355,
    pricePerDay: 900000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/JW+Marriott+Hotel+Mumbai+Juhu/@19.1021,-72.8271,17z',
    capacity: 1200,
  },
  {
    name: 'Sofitel Mumbai BKC',
    description: 'French art de vivre meets Mumbai\'s business district. Chic event spaces with sophisticated French-inspired décor. Ideal for corporate events and fashionable soirées.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 302,
    pricePerDay: 850000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/Sofitel+Mumbai+BKC/@19.0661,-72.8694,17z',
    capacity: 700,
  },
  {
    name: 'InterContinental Marine Drive',
    description: 'Seafacing luxury on the Queen\'s Necklace. Timeless elegance with Art Deco influences. The rooftop and ballroom offer breathtaking Marine Drive panoramas.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 59,
    pricePerDay: 700000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/InterContinental+Marine+Drive/@18.9362,-72.8239,17z',
    capacity: 300,
  },
  {
    name: 'Taj Lands End Mumbai',
    description: 'Dramatic seafront setting in Bandra with Arabian Sea views. Lush outdoor spaces and grand indoor ballrooms. A favourite for destination-style weddings in Mumbai.',
    city: 'Mumbai',
    state: 'Maharashtra',
    rooms: 493,
    pricePerDay: 1000000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/Taj+Lands+End/@19.0435,-72.8177,17z',
    capacity: 1000,
  },

  // DELHI / NCR (8)
  {
    name: 'The Leela Palace New Delhi',
    description: 'Regal palace hotel in Chanakyapuri inspired by Lutyens\' Delhi. Gold-leaf interiors, 9 acres of manicured gardens, and India\'s finest event infrastructure.',
    city: 'New Delhi',
    state: 'Delhi',
    rooms: 254,
    pricePerDay: 1800000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Leela+Palace+New+Delhi/@28.5972,-77.1744,17z',
    capacity: 2000,
  },
  {
    name: 'The Taj Mahal Hotel New Delhi',
    description: 'Legendary hospitality at the heart of New Delhi. Iconic Mansingh Road address with stunning ballrooms. The gold standard for diplomatic events and grand weddings.',
    city: 'New Delhi',
    state: 'Delhi',
    rooms: 294,
    pricePerDay: 1200000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/The+Taj+Mahal+Hotel+New+Delhi/@28.6006,-77.2200,17z',
    capacity: 1500,
  },
  {
    name: 'ITC Maurya New Delhi',
    description: 'The palace of ITC\'s luxury hospitality chain. Home to Bukhara and Dum Pukht. Stunning Mauryan-inspired architecture ideal for high-profile events.',
    city: 'New Delhi',
    state: 'Delhi',
    rooms: 439,
    pricePerDay: 1100000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/ITC+Maurya/@28.5978,-77.1817,17z',
    capacity: 1200,
  },
  {
    name: 'Hyatt Regency Delhi',
    description: 'Contemporary luxury in the diplomatic enclave. Multiple banquet halls, a grand lawn, and a dedicated weddings team. Known for seamless multi-day event hosting.',
    city: 'New Delhi',
    state: 'Delhi',
    rooms: 519,
    pricePerDay: 900000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/Hyatt+Regency+Delhi/@28.5933,-77.1704,17z',
    capacity: 2500,
  },
  {
    name: 'The Oberoi New Delhi',
    description: 'Minimalist luxury facing the golf course and the iconic Delhi skyline. Intimate yet grand — perfect for refined weddings and elite corporate retreats.',
    city: 'New Delhi',
    state: 'Delhi',
    rooms: 220,
    pricePerDay: 1400000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+New+Delhi/@28.6042,-77.2004,17z',
    capacity: 600,
  },
  {
    name: 'Trident Gurgaon',
    description: 'Striking contemporary design in the heart of Cyber City Gurgaon. Award-winning F&B, pillar-less ballrooms, and lush outdoor spaces for corporate and social events.',
    city: 'Gurugram',
    state: 'Haryana',
    rooms: 136,
    pricePerDay: 600000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/Trident+Gurgaon/@28.4935,-77.0870,17z',
    capacity: 800,
  },
  {
    name: 'Westin Gurgaon',
    description: 'Wellness-inspired luxury in the DLF Cyber Hub area. Superb banqueting facilities with natural light, outdoor terraces and Westin\'s signature service.',
    city: 'Gurugram',
    state: 'Haryana',
    rooms: 243,
    pricePerDay: 700000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/Westin+Gurgaon/@28.4994,-77.0888,17z',
    capacity: 1000,
  },
  {
    name: 'The Lalit New Delhi',
    description: 'Grand Indian luxury at Barakhamba Road with impressive columnated ballrooms. Inspired by India\'s arts and culture, ideal for vibrant and colourful celebrations.',
    city: 'New Delhi',
    state: 'Delhi',
    rooms: 461,
    pricePerDay: 750000,
    venueStyle: 'indian',
    googleUrl: 'https://www.google.com/maps/place/The+Lalit+New+Delhi/@28.6322,-77.2220,17z',
    capacity: 1500,
  },

  // JAIPUR (6)
  {
    name: 'Rambagh Palace',
    description: 'The "Jewel of Jaipur" — a former royal palace of the Maharaja of Jaipur. Breathtaking Mughal gardens, palatial rooms, and opulent event spaces for truly royal weddings.',
    city: 'Jaipur',
    state: 'Rajasthan',
    rooms: 78,
    pricePerDay: 2500000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Rambagh+Palace/@26.8981,-75.8095,17z',
    capacity: 1000,
  },
  {
    name: 'Jai Mahal Palace',
    description: 'An 18th-century palace in Jaipur set amid 18 acres of Mughal gardens. Elegant colonial architecture with modern amenities for heritage-themed events.',
    city: 'Jaipur',
    state: 'Rajasthan',
    rooms: 100,
    pricePerDay: 1500000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Jai+Mahal+Palace+Hotel/@26.9030,-75.8070,17z',
    capacity: 800,
  },
  {
    name: 'Fairmont Jaipur',
    description: 'Grand Rajput-inspired design with modern luxury. Sprawling lawns, a royal pool, and ballrooms that evoke Rajputana grandeur. A standout venue for destination weddings.',
    city: 'Jaipur',
    state: 'Rajasthan',
    rooms: 245,
    pricePerDay: 1200000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Fairmont+Jaipur/@26.8547,-75.8163,17z',
    capacity: 1500,
  },
  {
    name: 'ITC Rajputana Jaipur',
    description: 'Rajputana architecture meets ITC\'s luxury service. Rich textile décor, vibrant Rajasthani hospitality, and grand event spaces make it ideal for traditional weddings.',
    city: 'Jaipur',
    state: 'Rajasthan',
    rooms: 216,
    pricePerDay: 900000,
    venueStyle: 'indian',
    googleUrl: 'https://www.google.com/maps/place/ITC+Rajputana/@26.9045,-75.7996,17z',
    capacity: 1200,
  },
  {
    name: 'Trident Jaipur',
    description: 'Set against the backdrop of the Aravalli hills with a beautiful lake. Understated luxury with authentic Rajasthani hospitality and well-appointed event facilities.',
    city: 'Jaipur',
    state: 'Rajasthan',
    rooms: 140,
    pricePerDay: 700000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Trident+Jaipur/@26.8748,-75.8204,17z',
    capacity: 600,
  },
  {
    name: 'The Oberoi Rajvilas',
    description: 'A luxurious fort-style retreat in Jaipur with tented villas and a royal spa. Intimate and exclusive — ideal for small, ultra-luxury weddings and private retreats.',
    city: 'Jaipur',
    state: 'Rajasthan',
    rooms: 71,
    pricePerDay: 3000000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+Rajvilas/@26.8500,-75.7933,17z',
    capacity: 400,
  },

  // UDAIPUR (5)
  {
    name: 'Taj Lake Palace',
    description: 'An ethereal white marble palace floating on Lake Pichola. Arguably India\'s most iconic hotel. Exclusive island access, royal courtyard, and unmatched romance for weddings.',
    city: 'Udaipur',
    state: 'Rajasthan',
    rooms: 83,
    pricePerDay: 4000000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Taj+Lake+Palace/@24.5755,-73.6806,17z',
    capacity: 300,
  },
  {
    name: 'The Oberoi Udaivilas',
    description: 'Built to resemble a royal Rajput palace on the banks of Lake Pichola. Lush courtyards, infinity pools, and exclusive private ghats. India\'s most celebrated luxury resort.',
    city: 'Udaipur',
    state: 'Rajasthan',
    rooms: 87,
    pricePerDay: 3500000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+Udaivilas/@24.5797,-73.6841,17z',
    capacity: 400,
  },
  {
    name: 'Taj Fateh Prakash Palace',
    description: 'A stunning palace within the City Palace complex with stunning Lake Pichola views. Hosting an event here means your guests dine where Maharajas once held court.',
    city: 'Udaipur',
    state: 'Rajasthan',
    rooms: 74,
    pricePerDay: 2000000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Taj+Fateh+Prakash+Palace/@24.5751,-73.6819,17z',
    capacity: 500,
  },
  {
    name: 'Trident Udaipur',
    description: 'Set on the shores of Pichola Lake with a natural island setting. Serene and romantic, with excellent banqueting on the lakeside lawns and elegant indoor spaces.',
    city: 'Udaipur',
    state: 'Rajasthan',
    rooms: 138,
    pricePerDay: 1200000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Trident+Udaipur/@24.5850,-73.6878,17z',
    capacity: 700,
  },
  {
    name: 'Radisson Blu Udaipur Palace Resort & Spa',
    description: 'Perched on a hilltop with spectacular lake and Aravalli views. Luxurious poolside lawns, banquet halls, and spa facilities. Ideal for multi-day wedding celebrations.',
    city: 'Udaipur',
    state: 'Rajasthan',
    rooms: 107,
    pricePerDay: 900000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Radisson+Blu+Udaipur+Palace+Resort+%26+Spa/@24.5911,-73.7077,17z',
    capacity: 600,
  },

  // GOA (5)
  {
    name: 'Taj Exotica Resort & Spa Goa',
    description: 'Spread across 56 acres of landscaped gardens on Benaulim Beach. Goa\'s most exclusive resort for beach weddings, sundowner corporate events, and destination celebrations.',
    city: 'Goa',
    state: 'Goa',
    rooms: 140,
    pricePerDay: 2000000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/Taj+Exotica+Resort+%26+Spa,+Goa/@15.2587,-73.9462,17z',
    capacity: 800,
  },
  {
    name: 'The Leela Goa',
    description: 'Sprawling resort on Mobor Beach with 75 acres of palm-fringed gardens and a lagoon. Multiple stunning outdoor event spaces for grand Goa destination weddings.',
    city: 'Goa',
    state: 'Goa',
    rooms: 206,
    pricePerDay: 1800000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Leela+Goa/@14.9172,-73.9379,17z',
    capacity: 1000,
  },
  {
    name: 'Park Hyatt Goa Resort and Spa',
    description: 'Indo-Portuguese colonial architecture meets contemporary luxury on Arossim Beach. Vibrant outdoor spaces, beachfront lawns, and an award-winning spa.',
    city: 'Goa',
    state: 'Goa',
    rooms: 250,
    pricePerDay: 1200000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Park+Hyatt+Goa+Resort+and+Spa/@15.1986,-73.9336,17z',
    capacity: 1000,
  },
  {
    name: 'Grand Hyatt Goa',
    description: 'Sprawling riverside luxury resort with Portuguese-inspired architecture. India\'s largest beach resort ballroom and stunning outdoor event spaces across 28 acres.',
    city: 'Goa',
    state: 'Goa',
    rooms: 348,
    pricePerDay: 1100000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Grand+Hyatt+Goa/@15.4985,-73.8004,17z',
    capacity: 1500,
  },
  {
    name: 'W Goa',
    description: 'Trendy, vibrant luxury on Vagator Beach. Bold design, WET deck pool parties, and Living Room ballroom. Perfect for younger, high-energy celebrations and music events.',
    city: 'Goa',
    state: 'Goa',
    rooms: 162,
    pricePerDay: 1300000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/W+Goa/@15.5966,-73.7440,17z',
    capacity: 600,
  },

  // HYDERABAD (4)
  {
    name: 'Taj Falaknuma Palace',
    description: 'A 19th-century Italian Palladian-style palace on a hilltop. Once home to the Nizam, now the grandest events venue in Hyderabad — unforgettable for royal-themed weddings.',
    city: 'Hyderabad',
    state: 'Telangana',
    rooms: 60,
    pricePerDay: 3000000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Taj+Falaknuma+Palace/@17.3323,-78.4626,17z',
    capacity: 500,
  },
  {
    name: 'The Park Hyderabad',
    description: 'Contemporary design hotel in the heart of the city. Vibrant event spaces with modern aesthetics. Ideal for corporate launches and fashionable social gatherings.',
    city: 'Hyderabad',
    state: 'Telangana',
    rooms: 268,
    pricePerDay: 800000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/The+Park+Hyderabad/@17.4312,-78.4539,17z',
    capacity: 700,
  },
  {
    name: 'ITC Kohenur Hyderabad',
    description: 'A LEED Platinum luxury hotel with stunning infinity pools and Hussain Sagar lake views. Grand ballrooms and outdoor spaces perfect for modern weddings and corporate events.',
    city: 'Hyderabad',
    state: 'Telangana',
    rooms: 275,
    pricePerDay: 1200000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/ITC+Kohenur+Hyderabad/@17.4499,-78.3811,17z',
    capacity: 1000,
  },
  {
    name: 'Marriott Hyderabad',
    description: 'Located at Tank Bund with Hussain Sagar views. Versatile pillar-free ballrooms and outdoor lakeside spaces. A trusted choice for multi-day corporate summits and celebrations.',
    city: 'Hyderabad',
    state: 'Telangana',
    rooms: 273,
    pricePerDay: 900000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/Marriott+Hotel+%26+Convention+Centre,+Hyderabad/@17.4465,-78.4661,17z',
    capacity: 2000,
  },

  // BENGALURU (4)
  {
    name: 'The Leela Palace Bengaluru',
    description: 'A spectacular palace hotel in HAL with Rajasthani-inspired architecture. The largest pillar-free banquet hall in Bengaluru and lush garden lawns for outdoor events.',
    city: 'Bengaluru',
    state: 'Karnataka',
    rooms: 357,
    pricePerDay: 1200000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Leela+Palace+Bengaluru/@12.9611,-77.6514,17z',
    capacity: 2000,
  },
  {
    name: 'ITC Windsor Bengaluru',
    description: 'Heritage Victorian manor near the golf course. Classic elegance with stone arches and ivy-covered façade. Ideal for understated luxury weddings and business conferences.',
    city: 'Bengaluru',
    state: 'Karnataka',
    rooms: 240,
    pricePerDay: 900000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/ITC+Windsor/@12.9725,-77.5943,17z',
    capacity: 800,
  },
  {
    name: 'Taj West End Bengaluru',
    description: 'A heritage hotel on 20 acres of manicured grounds in the heart of Bengaluru. Garden weddings under 100-year-old trees, colonial bungalows, and exceptional Taj service.',
    city: 'Bengaluru',
    state: 'Karnataka',
    rooms: 117,
    pricePerDay: 1100000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Taj+West+End,+Bengaluru/@12.9750,-77.5936,17z',
    capacity: 600,
  },
  {
    name: 'JW Marriott Bengaluru',
    description: 'Ultra-modern luxury in Vittal Mallya Road. Sky-high event spaces with city views, rooftop pool, and sleek ballrooms. Perfect for executive launches and chic celebrations.',
    city: 'Bengaluru',
    state: 'Karnataka',
    rooms: 285,
    pricePerDay: 1000000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/JW+Marriott+Hotel+Bengaluru/@12.9700,-77.5976,17z',
    capacity: 900,
  },

  // CHENNAI (3)
  {
    name: 'ITC Grand Chola Chennai',
    description: 'India\'s largest hotel by room count, inspired by the Chola dynasty. 50+ restaurants, a stunning 1.5-acre outdoor event space, and unrivalled conference facilities.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    rooms: 600,
    pricePerDay: 1200000,
    venueStyle: 'indian',
    googleUrl: 'https://www.google.com/maps/place/ITC+Grand+Chola/@12.9953,-80.2218,17z',
    capacity: 5000,
  },
  {
    name: 'Taj Coromandel Chennai',
    description: 'Landmark luxury hotel in Nungambakkam for over 50 years. Elegant ballrooms, lush lawns, and contemporary meeting spaces in the heart of Chennai\'s business district.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    rooms: 193,
    pricePerDay: 1000000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/Taj+Coromandel,+Chennai/@13.0603,-80.2531,17z',
    capacity: 1000,
  },
  {
    name: 'The Leela Palace Chennai',
    description: 'Stunning seafront palace hotel on the Bay of Bengal. Lavish interiors, expansive sea-facing lawns, and grand ballrooms with dramatic ocean backdrops.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    rooms: 326,
    pricePerDay: 1100000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Leela+Palace+Chennai/@13.0106,-80.2674,17z',
    capacity: 1500,
  },

  // KOLKATA (3)
  {
    name: 'Taj Bengal Kolkata',
    description: 'Kolkata\'s finest hotel on Belvedere Road with views of Victoria Memorial. Exquisite Bengal-inspired interiors, superb F&B, and versatile banquet spaces for royal celebrations.',
    city: 'Kolkata',
    state: 'West Bengal',
    rooms: 229,
    pricePerDay: 900000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Taj+Bengal/@22.5352,-88.3396,17z',
    capacity: 800,
  },
  {
    name: 'The Oberoi Grand Kolkata',
    description: 'A Victorian-era grande dame on Jawaharlal Nehru Road, operational since 1876. Stately colonial elegance with impeccable Oberoi service in the heart of the city.',
    city: 'Kolkata',
    state: 'West Bengal',
    rooms: 213,
    pricePerDay: 800000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+Grand+Kolkata/@22.5578,-88.3516,17z',
    capacity: 600,
  },
  {
    name: 'ITC Sonar Kolkata',
    description: 'A serene urban retreat spread across 3 acres of lush greenery near EM Bypass. Eco-sensitive design, extensive lawns, and modern banquet halls for memorable events.',
    city: 'Kolkata',
    state: 'West Bengal',
    rooms: 237,
    pricePerDay: 850000,
    venueStyle: 'modern',
    googleUrl: 'https://www.google.com/maps/place/ITC+Sonar/@22.5163,-88.3966,17z',
    capacity: 900,
  },

  // AGRA (2)
  {
    name: 'The Oberoi Amarvilas',
    description: 'Every room has an unobstructed view of the Taj Mahal. The most romantic event backdrop in the world — for weddings where the Taj Mahal literally watches over your ceremony.',
    city: 'Agra',
    state: 'Uttar Pradesh',
    rooms: 102,
    pricePerDay: 3500000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+Amarvilas/@27.1681,-78.0429,17z',
    capacity: 400,
  },
  {
    name: 'Taj Hotel & Convention Centre Agra',
    description: 'Modern luxury with Mughal-inspired design near the Taj Mahal. Extensive convention centre, multiple outdoor event spaces, and the full Taj service guarantee.',
    city: 'Agra',
    state: 'Uttar Pradesh',
    rooms: 294,
    pricePerDay: 1000000,
    venueStyle: 'luxury',
    googleUrl: 'https://www.google.com/maps/place/Taj+Hotel+%26+Convention+Centre,+Agra/@27.1804,-77.9991,17z',
    capacity: 2000,
  },

  // SHIMLA (2)
  {
    name: 'Wildflower Hall Shimla in the Himalayas',
    description: 'A former residence of Lord Kitchener perched at 8,250 ft in the Himalayas. Breathtaking mountain vistas, cedar forests, and an intimate colonial setting for exclusive events.',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    rooms: 85,
    pricePerDay: 2000000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/Wildflower+Hall/@31.1048,77.1855,17z',
    capacity: 200,
  },
  {
    name: 'The Oberoi Cecil Shimla',
    description: 'A heritage property in the heart of Shimla established in 1884. Timeless Edwardian architecture with Himalayan views — perfect for intimate mountain weddings.',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    rooms: 79,
    pricePerDay: 1500000,
    venueStyle: 'heritage',
    googleUrl: 'https://www.google.com/maps/place/The+Oberoi+Cecil/@31.1022,77.1704,17z',
    capacity: 300,
  },
];

const artists = [
  {
    name: 'Anchor Anupriya Kapoor',
    description: 'Bilingual emcee specialising in grand Indian weddings and corporate galas. Known for her warmth, humour, and ability to connect with diverse audiences across Hindi and English.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'emcee',
    priceRangeMin: 75000,
    priceRangeMax: 200000,
    googleUrl: 'https://www.google.com/search?q=Anupriya+Kapoor+Anchor+India',
  },
  {
    name: 'Rahul Subramanian',
    description: 'Stand-up comedian turned corporate entertainer. Razor-sharp observational comedy in English and Hindi. A crowd favourite at corporate parties and award nights.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'stand_up_comedian',
    priceRangeMin: 300000,
    priceRangeMax: 800000,
    googleUrl: 'https://www.google.com/search?q=Rahul+Subramanian+comedian',
  },
  {
    name: 'DJ Aqeel',
    description: 'Bollywood\'s legendary DJ with 20+ years of experience. Known for high-energy sets blending Bollywood hits, retro classics, and remixes. A staple at India\'s biggest parties.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'dj',
    priceRangeMin: 500000,
    priceRangeMax: 1500000,
    googleUrl: 'https://www.google.com/search?q=DJ+Aqeel+Bollywood',
  },
  {
    name: 'DJ NYK',
    description: 'One of India\'s top EDM and commercial DJs. Resident at major nightclubs and festivals. Crafts bespoke sets combining EDM, Bollywood, and international chart toppers.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'dj',
    priceRangeMin: 200000,
    priceRangeMax: 600000,
    googleUrl: 'https://www.google.com/search?q=DJ+NYK+India',
  },
  {
    name: 'Shankar Mahadevan Live Band',
    description: 'Grammy-winning composer Shankar Mahadevan with his live band. An unforgettable evening of Bollywood, sufi, and classical fusion. Premium entertainment for elite events.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'live_band',
    priceRangeMin: 5000000,
    priceRangeMax: 15000000,
    googleUrl: 'https://www.google.com/search?q=Shankar+Mahadevan+live+concert',
  },
  {
    name: 'Kailash Kher',
    description: 'Sufi-rock singer known for soulful anthems like Teri Deewani and Allah Ke Bande. His electrifying live performances bring profound emotion and energy to weddings and events.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'bollywood_celebrity',
    priceRangeMin: 3000000,
    priceRangeMax: 8000000,
    googleUrl: 'https://www.google.com/search?q=Kailash+Kher+live+performance',
  },
  {
    name: 'Neha Kakkar Live',
    description: 'India\'s most-streamed female singer with chart-toppers across a decade. Her high-energy live shows are a guaranteed hit at weddings, sangeets, and corporate parties.',
    city: 'Delhi',
    state: 'Delhi',
    artistType: 'bollywood_celebrity',
    priceRangeMin: 8000000,
    priceRangeMax: 25000000,
    googleUrl: 'https://www.google.com/search?q=Neha+Kakkar+live+concert',
  },
  {
    name: 'Strings of Shrutti — Classical Violin Ensemble',
    description: 'A duo of trained violinists performing Bollywood melodies, Western classical, and Hindi film compositions. Elegant ambient entertainment for cocktail hours and gala dinners.',
    city: 'Bengaluru',
    state: 'Karnataka',
    artistType: 'violinist',
    priceRangeMin: 80000,
    priceRangeMax: 200000,
    googleUrl: 'https://www.google.com/search?q=violin+ensemble+event+Bengaluru',
  },
  {
    name: 'Devang Patel — Saxophone & Jazz',
    description: 'Classically trained saxophonist with 15+ years of live performance experience. Jazz standards, Bollywood on sax, and custom compositions for sophisticated evening events.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'saxophonist',
    priceRangeMin: 60000,
    priceRangeMax: 150000,
    googleUrl: 'https://www.google.com/search?q=saxophone+player+events+Mumbai',
  },
  {
    name: 'Kalbeliya Folk Dance Troupe Jaipur',
    description: 'Authentic Rajasthani Kalbeliya serpent dancers from Jaipur. UNESCO-recognised folk art performed in traditional costume. Adds regal Rajputana flavour to any event.',
    city: 'Jaipur',
    state: 'Rajasthan',
    artistType: 'folk_dancer',
    priceRangeMin: 50000,
    priceRangeMax: 150000,
    googleUrl: 'https://www.google.com/search?q=Kalbeliya+dance+troupe+Jaipur',
  },
  {
    name: 'Bhangra Blaze — Punjabi Dance Troupe',
    description: 'High-octane Bhangra and Giddha group from Chandigarh. Trained in traditional Punjabi folk and fusion styles. Guaranteed to electrify sangeets and baraat processions.',
    city: 'Chandigarh',
    state: 'Punjab',
    artistType: 'folk_dancer',
    priceRangeMin: 80000,
    priceRangeMax: 200000,
    googleUrl: 'https://www.google.com/search?q=Bhangra+troupe+Chandigarh+events',
  },
  {
    name: 'Groovecraft — Bollywood Dance Troupe',
    description: 'Mumbai-based Bollywood and contemporary dance group performing to the latest hits. Slick choreography, dazzling costumes, and audience interaction for weddings and gala nights.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'bollywood_dancer',
    priceRangeMin: 100000,
    priceRangeMax: 300000,
    googleUrl: 'https://www.google.com/search?q=Bollywood+dance+troupe+Mumbai+events',
  },
  {
    name: 'Samba Seduction — International Dance Show',
    description: 'Trained Brazilian Samba and Belly dance performers. Vibrant international act ideal for fusion weddings, destination events, and cocktail soirées seeking a global flair.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'international_dancer',
    priceRangeMin: 150000,
    priceRangeMax: 400000,
    googleUrl: 'https://www.google.com/search?q=international+dance+show+events+India',
  },
  {
    name: 'Suresh Mudra — Live Sand Art',
    description: 'Acclaimed sand artist creating real-time animated stories on an illuminated table. Mesmerising storytelling medium for opening ceremonies, corporate milestones, and themed events.',
    city: 'Hyderabad',
    state: 'Telangana',
    artistType: 'sand_artist',
    priceRangeMin: 75000,
    priceRangeMax: 200000,
    googleUrl: 'https://www.google.com/search?q=sand+art+live+performance+India+events',
  },
  {
    name: 'Arpit Bala — Stand-up Comedy',
    description: 'Hindi stand-up comedian known for relatable content about family and relationships. Perfect for sangeet nights and corporate parties wanting clean, crowd-friendly humour.',
    city: 'Delhi',
    state: 'Delhi',
    artistType: 'stand_up_comedian',
    priceRangeMin: 150000,
    priceRangeMax: 400000,
    googleUrl: 'https://www.google.com/search?q=Arpit+Bala+comedian',
  },
  {
    name: 'The Dhol Foundation India',
    description: 'Energetic dhol players and Punjabi boliyan performers specialising in baraat entries and sangeet entertainment. Creates an unforgettable atmosphere with traditional percussion.',
    city: 'Amritsar',
    state: 'Punjab',
    artistType: 'dhol_artist',
    priceRangeMin: 40000,
    priceRangeMax: 120000,
    googleUrl: 'https://www.google.com/search?q=dhol+players+wedding+India',
  },
  {
    name: 'Samarth — Mentalist & Illusionist',
    description: 'India\'s leading corporate mentalist with mind-bending illusions and psychological demonstrations. A stunning after-dinner act that leaves audiences speechless at luxury events.',
    city: 'Mumbai',
    state: 'Maharashtra',
    artistType: 'illusionist',
    priceRangeMin: 200000,
    priceRangeMax: 600000,
    googleUrl: 'https://www.google.com/search?q=mentalist+illusionist+corporate+events+India',
  },
  {
    name: 'Drum Circle India — Percussion Experience',
    description: 'Interactive percussion workshops and drum circle experiences facilitated by professional percussionists. A unique team-building and celebration activity for 50–500 participants.',
    city: 'Bengaluru',
    state: 'Karnataka',
    artistType: 'percussion_artist',
    priceRangeMin: 100000,
    priceRangeMax: 300000,
    googleUrl: 'https://www.google.com/search?q=drum+circle+team+building+India+events',
  },
];

const vendors = [
  {
    name: 'Shaadi Décor by Isha',
    description: 'Award-winning decorator specialising in luxury floral and fabric installations for Indian weddings. Known for elaborate mandap designs and enchanting entrance decorations.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'decorator',
    priceRangeMin: 500000,
    priceRangeMax: 3000000,
    googleUrl: 'https://www.google.com/search?q=luxury+wedding+decorator+Mumbai',
  },
  {
    name: 'Decorwale Events',
    description: 'Delhi NCR\'s most sought-after event decorator. From intimate mehendi setups to 1,000-pax grand receptions. Specialises in floral carpets, LED art, and custom installations.',
    city: 'New Delhi',
    state: 'Delhi',
    vendorType: 'decorator',
    priceRangeMin: 400000,
    priceRangeMax: 2500000,
    googleUrl: 'https://www.google.com/search?q=Decorwale+Events+Delhi',
  },
  {
    name: 'StageSet Fabricators Mumbai',
    description: 'Premium fabricator specialising in large-scale stage design, truss structures, LED walls, and fibre installations. Trusted by India\'s top event companies for production-grade builds.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'fabricator',
    priceRangeMin: 800000,
    priceRangeMax: 5000000,
    googleUrl: 'https://www.google.com/search?q=stage+fabricator+event+production+Mumbai',
  },
  {
    name: 'Wizcraft International',
    description: 'India\'s premier full-service event production and entertainment company. Handles complete event production including AV, staging, artist management, and creative concepts for premium events.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'av_production',
    priceRangeMin: 2000000,
    priceRangeMax: 20000000,
    googleUrl: 'https://www.google.com/search?q=Wizcraft+International+events',
  },
  {
    name: 'Encompass Events',
    description: 'Award-winning event management agency handling India\'s largest corporate events, product launches, and luxury weddings. Full-service planning from concept to execution.',
    city: 'New Delhi',
    state: 'Delhi',
    vendorType: 'wedding_planner',
    priceRangeMin: 1500000,
    priceRangeMax: 15000000,
    googleUrl: 'https://www.google.com/search?q=Encompass+Events+Delhi',
  },
  {
    name: 'WeddingNama Planning',
    description: 'Boutique luxury wedding planning studio in Delhi. Handles destination weddings across Rajasthan, Goa, and Dubai. Known for curated experiences and meticulous attention to detail.',
    city: 'New Delhi',
    state: 'Delhi',
    vendorType: 'wedding_planner',
    priceRangeMin: 1000000,
    priceRangeMax: 8000000,
    googleUrl: 'https://www.google.com/search?q=WeddingNama+wedding+planning+Delhi',
  },
  {
    name: 'Joseph Radhik Photography',
    description: 'India\'s most celebrated wedding photographer. Featured in Vogue, Harper\'s Bazaar. Captures weddings with a cinematic editorial eye. Books up 18 months in advance.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    vendorType: 'photographer',
    priceRangeMin: 800000,
    priceRangeMax: 3000000,
    googleUrl: 'https://www.google.com/search?q=Joseph+Radhik+wedding+photographer',
  },
  {
    name: 'The Wedding Filmer',
    description: 'India\'s leading wedding cinematography studio. Their films have 100M+ YouTube views. Creates extraordinary wedding films that feel like a Bollywood production.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'photographer',
    priceRangeMin: 600000,
    priceRangeMax: 2500000,
    googleUrl: 'https://www.google.com/search?q=The+Wedding+Filmer+India',
  },
  {
    name: 'SFX India — Cold Pyro & Entry Effects',
    description: 'Specialists in cold pyrotechnics, confetti cannons, CO2 jets, and bride/groom entry effects. Serves luxury weddings across India with trained technicians and safety protocols.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'sfx_provider',
    priceRangeMin: 100000,
    priceRangeMax: 800000,
    googleUrl: 'https://www.google.com/search?q=SFX+cold+pyro+wedding+effects+India',
  },
  {
    name: 'Molecular Bar India',
    description: 'India\'s pioneering molecular mixology bar service. Liquid nitrogen cocktails, smoking drinks, and edible garnishes. A sensational F&B experience for luxury event guests.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'molecular_bar',
    priceRangeMin: 200000,
    priceRangeMax: 800000,
    googleUrl: 'https://www.google.com/search?q=molecular+bar+cocktails+events+India',
  },
  {
    name: 'Rathi Furniture Rentals',
    description: 'Delhi\'s largest event furniture rental company. Extensive inventory of luxury banquet chairs, Chivari chairs, vintage sofas, and custom high-tables for all event types.',
    city: 'New Delhi',
    state: 'Delhi',
    vendorType: 'furniture_rental',
    priceRangeMin: 100000,
    priceRangeMax: 600000,
    googleUrl: 'https://www.google.com/search?q=event+furniture+rental+Delhi',
  },
  {
    name: 'Greentech Genset & Lighting',
    description: 'Reliable generator and lighting equipment supplier for events. Silent DG sets, distribution boards, and full power backup solutions for uninterrupted event operations.',
    city: 'Gurugram',
    state: 'Haryana',
    vendorType: 'genset_lighting',
    priceRangeMin: 80000,
    priceRangeMax: 400000,
    googleUrl: 'https://www.google.com/search?q=generator+rental+events+Gurgaon',
  },
  {
    name: 'MapleMaps Travel — Event Logistics',
    description: 'Full-service travel and logistics partner for destination weddings and corporate offsites. Handles group air bookings, hotel blocks, ground transport, and guest travel management.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'travel_agent',
    priceRangeMin: 200000,
    priceRangeMax: 2000000,
    googleUrl: 'https://www.google.com/search?q=destination+wedding+travel+agent+India',
  },
  {
    name: 'Royal Valet & Security Services',
    description: 'Professional valet parking and event security for luxury events. Trained personnel in formal attire, real-time car tracking, and discreet security protocols for high-profile guests.',
    city: 'New Delhi',
    state: 'Delhi',
    vendorType: 'valet_security',
    priceRangeMin: 80000,
    priceRangeMax: 300000,
    googleUrl: 'https://www.google.com/search?q=valet+parking+event+security+Delhi',
  },
  {
    name: 'Pixelmapp — Projection Mapping India',
    description: 'Pioneers in architectural projection mapping in India. Creates breathtaking visual narratives on building facades, stages, and props for a truly immersive event experience.',
    city: 'Hyderabad',
    state: 'Telangana',
    vendorType: 'projection_mapping',
    priceRangeMin: 500000,
    priceRangeMax: 3000000,
    googleUrl: 'https://www.google.com/search?q=projection+mapping+events+India',
  },
  {
    name: 'LuxePacks — Gifting & Packaging',
    description: 'Curated luxury gifting solutions for corporate events and weddings. Custom hampers, branded packaging, and experiential gift boxes sourced from premium artisans across India.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'luxury_gifting',
    priceRangeMin: 200000,
    priceRangeMax: 1500000,
    googleUrl: 'https://www.google.com/search?q=luxury+corporate+gifting+events+India',
  },
  {
    name: 'GuestPro — Hospitality & RSVP Management',
    description: 'End-to-end guest management for luxury events. Physical RSVP teams, guest tracking systems, welcome desks, and shadow service for the bridal couple.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'hospitality',
    priceRangeMin: 150000,
    priceRangeMax: 800000,
    googleUrl: 'https://www.google.com/search?q=event+guest+management+hospitality+India',
  },
  {
    name: 'AutoLux — Luxury Car Rentals',
    description: 'Premium fleet of Mercedes, BMW, Range Rover, and vintage cars for bridal entries and VIP transfers. Professionally uniformed chauffeurs across all major Indian cities.',
    city: 'Mumbai',
    state: 'Maharashtra',
    vendorType: 'rental_car',
    priceRangeMin: 50000,
    priceRangeMax: 400000,
    googleUrl: 'https://www.google.com/search?q=luxury+car+rental+wedding+India',
  },
  {
    name: 'Presto AV — Audio Visual Production',
    description: 'Pan-India AV production house. LED walls, line array sound systems, intelligent lighting, and live streaming. Trusted for large-scale corporate conferences and award ceremonies.',
    city: 'New Delhi',
    state: 'Delhi',
    vendorType: 'av_production',
    priceRangeMin: 300000,
    priceRangeMax: 3000000,
    googleUrl: 'https://www.google.com/search?q=AV+production+house+event+Delhi',
  },
  {
    name: 'Ashiyana Tent & Décor',
    description: 'Established tent and décor contractor across Rajasthan. Provides traditional shamianas, contemporary tensile structures, and full furniture packages for outdoor wedding venues.',
    city: 'Jaipur',
    state: 'Rajasthan',
    vendorType: 'decorator',
    priceRangeMin: 300000,
    priceRangeMax: 1500000,
    googleUrl: 'https://www.google.com/search?q=tent+decor+contractor+Jaipur+wedding',
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  // Clear existing data
  await prisma.vendor.deleteMany();
  await prisma.artist.deleteMany();
  await prisma.venue.deleteMany();

  // Seed venues
  console.log(`  → Seeding ${venues.length} venues...`);
  await prisma.venue.createMany({ data: venues });

  // Seed artists
  console.log(`  → Seeding ${artists.length} artists...`);
  await prisma.artist.createMany({ data: artists });

  // Seed vendors
  console.log(`  → Seeding ${vendors.length} vendors...`);
  await prisma.vendor.createMany({ data: vendors });

  console.log('✅ Seed complete!');
  console.log(`   Venues: ${venues.length}`);
  console.log(`   Artists: ${artists.length}`);
  console.log(`   Vendors: ${vendors.length}`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
